<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ps2tex</AssemblyName>
    <RootNamespace>Ps2TextureGrabber</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
